apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  aws_access_key_id: QVNJQVRPTFpWWFA1M05GN01NNjU=
  aws_secret_access_key: aUVmclN2SnBDUlBQbDZlTTFzOVUvV3dCSU1NN05nYnArSy81RXpoRg==